### ISSUE TITLE
CMake Warning (dev) at CMakeLists.txt:9 (project)

### ISSUE THREAD

**Issue by h20gg702** [Xinglab/rmats-turbo#305]
I got following error when try to `/build_rmats`
Could you solve this problem?

`cd bamtools; mkdir -p build; cd build; cmake ..; make;
CMake Warning (dev) at CMakeLists.txt:9 (project):
  cmake_minimum_required() should be called prior to this top-level project()
  call.  Please see the cmake-commands(7) manual for usage documentation of
  both commands.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Deprecation Warning at CMakeLists.txt:12 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Configuring done (0.0s)
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   BamTools

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done (0.1s)
-- Build files have been written to: /Users/yoshiakisato/rmats-turbo/bamtools/build
[  0%] Built target SharedHeaders
[ 38%] Built target BamTools
[ 76%] Built target BamTools-static
[ 76%] Built target APIHeaders
[ 76%] Built target AlgorithmsHeaders
[ 80%] Built target jsoncpp
[ 85%] Built target BamTools-utils
[ 86%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_resolve.cpp.o
In file included from /Users/yoshiakisato/rmats-turbo/bamtools/src/toolkit/bamtools_resolve.cpp:12:
In file included from /Users/yoshiakisato/rmats-turbo/bamtools/src/api/BamReader.h:14:
In file included from /Users/yoshiakisato/rmats-turbo/bamtools/src/api/BamAlignment.h:15:
/Users/yoshiakisato/rmats-turbo/bamtools/src/api/BamConstants.h:129:25: warning: implicit conversion from 'int' to 'const char' changes value from 139 to -117 [-Wconstant-conversion]
const char GZIP_ID2   = 139;
           ~~~~~~~~     ^~~
/Users/yoshiakisato/rmats-turbo/bamtools/src/api/BamConstants.h:132:25: warning: implicit conversion from 'int' to 'const char' changes value from 255 to -1 [-Wconstant-conversion]
const char OS_UNKNOWN = 255;
           ~~~~~~~~~~   ^~~
In file included from /Users/yoshiakisato/rmats-turbo/bamtools/src/toolkit/bamtools_resolve.cpp:12:
In file included from /Users/yoshiakisato/rmats-turbo/bamtools/src/api/BamReader.h:14:
/Users/yoshiakisato/rmats-turbo/bamtools/src/api/BamAlignment.h:581:9: warning: variable 'elementLength' set but not used [-Wunused-but-set-variable]
    int elementLength = 0;
        ^
/Users/yoshiakisato/rmats-turbo/bamtools/src/toolkit/bamtools_resolve.cpp:413:36: error: no matching function for call to 'make_pair'
        resolver.ReadNames.insert( make_pair<string,bool>(fields[1], true) ) ;
                                   ^~~~~~~~~~~~~~~~~~~~~~
/Users/yoshiakisato/rmats_pairadise_conda_env/bin/../include/c++/v1/__utility/pair.h:542:1: note: candidate function template not viable: expects an rvalue for 1st argument
make_pair(_T1&& __t1, _T2&& __t2)
^
/Users/yoshiakisato/rmats-turbo/bamtools/src/toolkit/bamtools_resolve.cpp:610:24: error: no matching function for call to 'make_pair'
    readGroups.insert( make_pair<string, ReadGroupResolver>(name, resolver) );
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/yoshiakisato/rmats_pairadise_conda_env/bin/../include/c++/v1/__utility/pair.h:542:1: note: candidate function template not viable: 1st argument ('const std::string' (aka 'const basic_string<char>')) would lose const qualifier
make_pair(_T1&& __t1, _T2&& __t2)
^
/Users/yoshiakisato/rmats-turbo/bamtools/src/toolkit/bamtools_resolve.cpp:1017:41: error: no matching function for call to 'make_pair'
        else resolver.ReadNames.insert( make_pair<string, bool>(al.Name, isCurrentMateUnique) );
                                        ^~~~~~~~~~~~~~~~~~~~~~~
/Users/yoshiakisato/rmats_pairadise_conda_env/bin/../include/c++/v1/__utility/pair.h:542:1: note: candidate function template not viable: expects an rvalue for 1st argument
make_pair(_T1&& __t1, _T2&& __t2)
^
/Users/yoshiakisato/rmats-turbo/bamtools/src/toolkit/bamtools_resolve.cpp:1049:30: error: no matching function for call to 'make_pair'
        m_readGroups.insert( make_pair<string, ReadGroupResolver>(rg.ID, ReadGroupResolver()) );
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/yoshiakisato/rmats_pairadise_conda_env/bin/../include/c++/v1/__utility/pair.h:542:1: note: candidate function template not viable: 1st argument ('const std::string' (aka 'const basic_string<char>')) would lose const qualifier
make_pair(_T1&& __t1, _T2&& __t2)
^
3 warnings and 4 errors generated.
make[3]: *** [src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_resolve.cpp.o] Error 1
make[2]: *** [src/toolkit/CMakeFiles/bamtools_cmd.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [build] Error 2`

**Comment by EricKutschera** [comment]
The warnings should be fine to ignore. The errors all are `no matching function for call to 'make_pair'`. There was a change introduced in rmats v4.1.1 that set the c++ version for the bamtools build: https://github.com/Xinglab/rmats-turbo/blob/8b168116c1594d7e02d764ae14a5ef28dbf38de1/bamtools/CMakeLists.txt#L43

Based on the error message I think the compiler was trying to use c++11 or newer, I think the code needs to use c++03. Are you building from the latest master branch of rmats?

The build should print a section giving the compiler path and version. I think the build should work with gcc and g++ version 5.4 or later. You can set environment variables to use specific compiler paths: https://github.com/Xinglab/rmats-turbo/blob/v4.1.2/setup_environment.sh#L29

**Comment by h20gg702** [comment]
Thank you for reply. I downloaded from source and try to set environment as following 
 `FC="$(which gfortran)"
CC="$(which gcc)"
CXX="$(which g++)"`
but still have same error. and `gcc --version
gcc-13 (Homebrew GCC 13.1.0) 13.1.0` and `g++ --version
g++-13 (Homebrew GCC 13.1.0) 13.1.0`

`/Users/yoshiakisato/rmats_turbo_v4_1_2/bamtools/src/toolkit/bamtools_resolve.cpp:413:36: error: no matching function for call to 'make_pair'
        resolver.ReadNames.insert( make_pair<string,bool>(fields[1], true) ) ;
                                   ^~~~~~~~~~~~~~~~~~~~~~
/Users/yoshiakisato/rmats_turbo_v4_1_2/conda_envs/rmats/bin/../include/c++/v1/__utility/pair.h:542:1: note: candidate function template not viable: expects an rvalue for 1st argument
make_pair(_T1&& __t1, _T2&& __t2)
^
/Users/yoshiakisato/rmats_turbo_v4_1_2/bamtools/src/toolkit/bamtools_resolve.cpp:610:24: error: no matching function for call to 'make_pair'
    readGroups.insert( make_pair<string, ReadGroupResolver>(name, resolver) );
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/yoshiakisato/rmats_turbo_v4_1_2/conda_envs/rmats/bin/../include/c++/v1/__utility/pair.h:542:1: note: candidate function template not viable: 1st argument ('const std::string' (aka 'const basic_string<char>')) would lose const qualifier
make_pair(_T1&& __t1, _T2&& __t2)
^
/Users/yoshiakisato/rmats_turbo_v4_1_2/bamtools/src/toolkit/bamtools_resolve.cpp:1017:41: error: no matching function for call to 'make_pair'
        else resolver.ReadNames.insert( make_pair<string, bool>(al.Name, isCurrentMateUnique) );
                                        ^~~~~~~~~~~~~~~~~~~~~~~
/Users/yoshiakisato/rmats_turbo_v4_1_2/conda_envs/rmats/bin/../include/c++/v1/__utility/pair.h:542:1: note: candidate function template not viable: expects an rvalue for 1st argument
make_pair(_T1&& __t1, _T2&& __t2)
^
/Users/yoshiakisato/rmats_turbo_v4_1_2/bamtools/src/toolkit/bamtools_resolve.cpp:1049:30: error: no matching function for call to 'make_pair'
        m_readGroups.insert( make_pair<string, ReadGroupResolver>(rg.ID, ReadGroupResolver()) );
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/yoshiakisato/rmats_turbo_v4_1_2/conda_envs/rmats/bin/../include/c++/v1/__utility/pair.h:542:1: note: candidate function template not viable: 1st argument ('const std::string' (aka 'const basic_string<char>')) would lose const qualifier
make_pair(_T1&& __t1, _T2&& __t2)
^
3 warnings and 4 errors generated.
make[3]: *** [src/toolkit/CMakeFiles/bamtools_cmd.dir/build.make:188: src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_resolve.cpp.o] Error 1
make[3]: Leaving directory '/Users/yoshiakisato/rmats_turbo_v4_1_2/bamtools/build'
make[2]: *** [CMakeFiles/Makefile2:452: src/toolkit/CMakeFiles/bamtools_cmd.dir/all] Error 2
make[2]: Leaving directory '/Users/yoshiakisato/rmats_turbo_v4_1_2/bamtools/build'
make[1]: *** [Makefile:136: all] Error 2
make[1]: Leaving directory '/Users/yoshiakisato/rmats_turbo_v4_1_2/bamtools/build'
make: *** [Makefile:3: build] Error 2`

also, when I downloaded from github by git clone, and try to build,
I got following error.

`./build_rmats                     
cd bamtools; mkdir -p build; cd build; cmake ..; make;
CMake Warning (dev) at CMakeLists.txt:9 (project):
  cmake_minimum_required() should be called prior to this top-level project()
  call.  Please see the cmake-commands(7) manual for usage documentation of
  both commands.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Deprecation Warning at CMakeLists.txt:12 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Configuring done (0.0s)
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   BamTools

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done (0.1s)
-- Build files have been written to: /Users/yoshiakisato/rmats-turbo/bamtools/build
[  0%] Built target SharedHeaders
[  1%] Linking CXX shared library /Users/yoshiakisato/rmats-turbo/bamtools/lib/libbamtools.dylib
[ 38%] Built target BamTools
[ 76%] Built target BamTools-static
[ 76%] Built target APIHeaders
[ 76%] Built target AlgorithmsHeaders
[ 80%] Built target jsoncpp
[ 85%] Built target BamTools-utils
[ 86%] Linking CXX executable /Users/yoshiakisato/rmats-turbo/bamtools/bin/bamtools
[100%] Built target bamtools_cmd
# rm -f to ignore nonexistent files since *.dylib will only exist for mac
cd bamtools/lib; rm -f *.so *.so.* *.dylib
cd rMATS_C; make;
gcc: aliased to gcc-13 -I/opt/homebrew/Cellar/gsl/2.7.1/include -Wall -O2 -msse2 -funroll-loops -fopenmp -o rMATSexe src/main.c src/myfunc.c src/util.c lbfgs_scipy/lbfgsb.o lbfgs_scipy/linpack.o lbfgs_scipy/timer.o -L/opt/homebrew/Cellar/gsl/2.7.1/lib -lgsl -lgslcblas -lm -lgfortran -lgsl -lgslcblas -lgomp -lblas -llapack
make[1]: gcc:: No such file or directory
make[1]: *** [rMATSexe] Error 1
make: *** [build] Error 2`

I am a beginner in this kind of analysis, I need your help more, Thanks.

**Comment by h20gg702** [comment]
I suggested this error is similar to isuue#11, so I tried `CXXFLAGS="-std=c++03" ./build_rmats`, but still get same error.
also, tried `export CC="gcc" ` , or `export CXX="g++" ` as I have added `alias gcc='gcc-13'` and `alias g++='g++-13'` in ~/.bashrc, but still get same error.

**Comment by h20gg702** [comment]
Thanks! it works.
